### ISSUE TITLE
Problem on following the ABP framework guide to create sample "SimpleTaskSystem"

### ISSUE THREAD

**Issue by winkyz** [aspnetboilerplate/aspnetboilerplate-samples#47]
Follows the ABP guide:
https://aspnetboilerplate.com/Pages/Articles/Introduction-With-AspNet-MVC-Web-API-EntityFramework-and-AngularJs/index.html

It is OK on steps "Create the application from boilerplate template",  "Create entities" and "Create DbContext".
But I was blocked at "Create Database Migrations", it is OK to Build entire solution, but runs the command  Add-Migration "InitialCreate"  on Package Manager Console, I always get error below:

PM> Add-Migration "InitialCreate"
System.IO.FileLoadException: Could not load file or assembly 'Castle.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=407dd0808d44fbdc' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
File name: 'Castle.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=407dd0808d44fbdc'
   at System.Signature.GetSignature(Void* pCorSig, Int32 cCorSig, RuntimeFieldHandleInternal fieldHandle, IRuntimeMethodInfo methodHandle, RuntimeType declaringType)
   at System.Reflection.RuntimeMethodInfo.FetchNonReturnParameters()
   at System.Reflection.RuntimeMethodInfo.GetParametersNoCopy()
   at System.Reflection.RuntimePropertyInfo.GetIndexParametersNoCopy()
   at System.Reflection.RuntimePropertyInfo.GetIndexParameters()
   at System.Data.Entity.Internal.DbSetDiscoveryService.<GetSets>b__0(PropertyInfo p)
   at System.Linq.Enumerable.<>c__DisplayClass6_0`1.<CombinePredicates>b__0(TSource x)
   at System.Linq.Enumerable.WhereArrayIterator`1.MoveNext()
   at System.Data.Entity.Internal.DbSetDiscoveryService.GetSets()
   at System.Data.Entity.Internal.DbSetDiscoveryService.InitializeSets()
   at System.Data.Entity.DbContext.InitializeLazyInternalContext(IInternalConnection internalConnection, DbCompiledModel model)
   at System.Data.Entity.DbContext..ctor(String nameOrConnectionString)
   at Abp.EntityFramework.AbpDbContext..ctor(String nameOrConnectionString)
   at SimpleTaskSystem.EntityFramework.SimpleTaskSystemDbContext..ctor() in C:\Users\Atlas\Downloads\SimpleTaskSystem\3.4.0\src\SimpleTaskSystem.EntityFramework\EntityFramework\SimpleTaskSystemDbContext.cs:line 19
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Data.Entity.Infrastructure.DbContextInfo.CreateInstance()
   at System.Data.Entity.Infrastructure.DbContextInfo..ctor(Type contextType, DbProviderInfo modelProviderInfo, AppConfig config, DbConnectionInfo connectionInfo, Func`1 resolver)
   at System.Data.Entity.Migrations.DbMigrator..ctor(DbMigrationsConfiguration configuration, DbContext usersContext, DatabaseExistenceState existenceState, Boolean calledByCreateDatabase)
   at System.Data.Entity.Migrations.DbMigrator..ctor(DbMigrationsConfiguration configuration)
   at System.Data.Entity.Migrations.Design.MigrationScaffolder..ctor(DbMigrationsConfiguration migrationsConfiguration)
   at System.Data.Entity.Migrations.Design.ToolingFacade.ScaffoldRunner.RunCore()
   at System.Data.Entity.Migrations.Design.ToolingFacade.BaseRunner.Run()

Could not load file or assembly 'Castle.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=407dd0808d44fbdc' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

I am a newer on .Net Web Development, Is here anyone can help me? thanks very much.

**Comment by ismcagdas** [comment]
@winkyz can you try this https://github.com/aspnetboilerplate/aspnetboilerplate/issues/2902#issuecomment-358182646 ?

**Comment by winkyz** [comment]
@ismcagdas 
Thanks for your response, but the solution doesn't works for my problem. 
I finally get rid of this by recreate and download a new project template.
