### ISSUE TITLE
HTTPS

### ISSUE THREAD

**Issue by newprogrammer1991** [aspnetboilerplate/aspnetboilerplate-samples#69]
Please help!!! With http work(https work only on browser part) . Prerender failed
![image](https://user-images.githubusercontent.com/25803072/57873569-4775e380-7817-11e9-80d3-20ba22d090c2.png)

**Comment by ismcagdas** [comment]
@newprogrammer1991 could you give some more details ? 

* Your project type and version
* error message

**Comment by newprogrammer1991** [comment]
Angular 5 , Aspnet Core 2.1

//// 
Error 
Microsoft.AspNetCore.NodeServices.HostingModels.NodeInvocationException: Prerendering timed out after 30000ms because the boot function in 'ClientApp/dist-server/main.bundle.js' returned a promise that did not resolve or reject. Make sure that your boot function always resolves or rejects its promise. You can change the timeout value using the 'asp-prerender-timeout' tag helper.

at Microsoft.AspNetCore.NodeServices.HostingModels.HttpNodeInstance.InvokeExportAsync[T](NodeInvocationInfo invocationInfo, CancellationToken cancellationToken)
at Microsoft.AspNetCore.NodeServices.HostingModels.OutOfProcessNodeInstance.InvokeExportAsync[T](CancellationToken cancellationToken, String moduleName, String exportNameOrNull, Object[] args)
at Microsoft.AspNetCore.NodeServices.NodeServicesImpl.InvokeExportWithPossibleRetryAsync[T](String moduleName, String exportedFunctionName, Object[] args, Boolean allowRetry, CancellationToken cancellationToken)
at Microsoft.AspNetCore.NodeServices.NodeServicesImpl.InvokeExportWithPossibleRetryAsync[T](String moduleName, String exportedFunctionName, Object[] args, Boolean allowRetry, CancellationToken cancellationToken)
at Microsoft.AspNetCore.Builder.SpaPrerenderingExtensions.<>c__DisplayClass0_0.<<UseSpaPrerendering>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
at barnasnorge.Startup.<>c.<<Configure>b__7_0>d.MoveNext() in C:\Users\ALI\Documents\barnars_admin\barnasnorge-no\barnasnorge\Startup.cs:line 191
--- End of stack trace from previous location where exception was thrown ---
at barnasnorge.RedirectMiddleware.Invoke(HttpContext context, IRedirectUrlRepository redirectRepo) in C:\Users\ALI\Documents\barnars_admin\barnasnorge-no\barnasnorge\RedirectMiddleware.cs:line 44
at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.Invoke(HttpContext context)
at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
at Microsoft.AspNetCore.Server.IISIntegration.IISMiddleware.Invoke(HttpContext httpContext)
at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)

**Comment by ismcagdas** [comment]
Have you downloaded your project from https://aspnetboilerplate.com/Templates ?

**Comment by newprogrammer1991** [comment]
from microsoft page

**Comment by ismcagdas** [comment]
So, what is the relation between your project and ABP Framework ?

**Comment by newprogrammer1991** [comment]
https://docs.microsoft.com/ru-ru/aspnet/core/client-side/spa/angular?view=aspnetcore-2.2&tabs=visual-studio

**Comment by ismcagdas** [comment]
@newprogrammer1991 sorry I don't have any experience with that and this issue is related to ASP.NET Core. So you can try to create an issue on its own repository.
